---
title: "02 Working Paper"
author: "Nate Breznau & Hung H.V. Nguyen"
date: "`r Sys.Date()`"
output: html_document
---

## R Markdown

```{r setup}

source("R/build_causal_matrix.R")
source("R/build_formula_matrix.R")
source("R/keep_minimal.R")
```

## Generate Model Multiverse

### Input variables

Generate causal matrix

```{r models}
inputs <- list(nodes=c("a","b","c","d"), timing=c(0,-1,-2,-2),
              types=c("otc","test","ctr","ctr"))

causal_matrix <- build_causal_matrix(inputs)
```

### Derive formulas

Generate formula matrix

```{r formula_matrix}

formula_matrix <- build_formula_matrix(causal_matrix)
```

### Add extra plots

```{r xmodels}
formula_matrix <- as.data.frame(formula_matrix)

# Model 3
formula_matrix[(nrow(formula_matrix)+1),] <- c("X4 ~ Y + Xtest,Y ~ X2 + Xtest,Xtest ~ X2 + X1", as.numeric(nrow(formula_matrix)+1))

# Model 5
formula_matrix[(nrow(formula_matrix)+1),] <- c("Y ~ X2 + Xtest,X3 ~ X2,Xtest ~ X3 + X2 + X1", as.numeric(nrow(formula_matrix)+1))

```


### Derive plots

#### Generate DAG formulas

```{r viz}
coords <- list(
    x = c(X4 = 1.5, Y = 1, Xtest = 0, X1 = -1, X2 = -1, X3 = -0.5),
    y = c(X4 = 1, Y = 0, Xtest = 0, X1 = -1, X2 = 1, X3 = 1)
)

additional_args <- list(
    exposure="Xtest",
    outcome="Y",
    coords = coords
)

full_matrix <- formula_matrix
full_matrix[8,1] <- "Y ~ X2 + Xtest, Xtest ~ X2, X1 ~ X1" # this still doesn't work, the plotting drops the X1
full_matrix_dags <- list()

# note that dagitty uses its own type of object, this means they need to be stored separately in a list
for (f in 1:nrow(formula_matrix)) {
    print(f)
    fvector <- strsplit(unlist(formula_matrix[f,1]), ",")[[1]]
    # create dag object syntax
    dag <- do.call(dagify, c(lapply(fvector, as.formula), additional_args))
    model <- full_matrix$model[f]
    full_matrix_dags[[model]] <- dag
    # extract adjustment sets
    mas <- adjustmentSets(dag, exposure = "Xtest", outcome = "Y", effect = "direct")
    mas <- ifelse(mas == "list()", "none", mas)
    full_matrix$mas[f] <- mas
}
```

#### DAG Plots

Model 1 = 22 (Version B = 21)
Model 2 = 1
Model 3 = 33
Model 4 = 8 
Model 5 = 34
Model 6 = 18

```{r plots}

# until build formula is updated X1 does not appear in the plot if it is not connected to anything

for (l in 1:length(full_matrix_dags)){
    p <- paste0("p",l)
    assign(p, plot(full_matrix_dags[[l]]))
}


```

