---
title: "R Notebook"
output: html_notebook
---

```{r setup}
source("R/build_causal_matrix.R")
source("R/build_formula_matrix.R")
source("R/keep_minimal.R")
```

## Build causal matrix
```{r causal_matrix}
## Inputs take the form of a named list. Nodes can take any name and will be transformed into X1-Xn based on its timing. Types include "ctr", "test", or "otc".
inputs <- list(nodes=c("a","b","c","d","e"), timing=c(-3,-3,-2,-1,0),
              types=c("ctr","ctr","ctr","test","otc"))

causal_matrix <- build_causal_matrix(inputs)
```


## Build formula_matrix
```{r formula_matrix}

formula_matrix <- build_formula_matrix(causal_matrix)
```

## Remove Xs which do not belong to the MAS from each model and remove duplicated models deriving from this action

```{r keep_minimal}
reduced_causal_matrix <- keep_minimal(formula_matrix, causal_matrix)
reduced_formula_matrix <- build_formula_matrix(reduced_causal_matrix)

```

## Visualizations

```{r viz}
additional_args <- list(
    exposure="Xtest",
    outcome="Y"
)
formulas_vector <- strsplit(unlist(reduced_formula_matrix[67,1]), ",")[[1]]
dag <- do.call(dagify, c(lapply(formulas_vector, as.formula), additional_args))


formulas_vector <- strsplit(unlist(reduced_formula_matrix[12,1]), ",")[[1]]
dag2 <- do.call(dagify, c(lapply(formulas_vector, as.formula), additional_args))

```

```{r graph_1}
plot(graphLayout(dag))
```

```{r graph_2}
plot(graphLayout(dag2))
```

